spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

security:
  jwt:
    secret: pyj2QjD4mb7Rm7i4jo2Dx8XdTgmV5fIQ4JRORssXthc=

app:
  discounts:
    high-line-item:
      threshold: 100.00
      amount: 50.00
    high-value-order:
      threshold: 500.00
      rate: 0.05
    premium-user:
      rate: 0.10